### PR TITLE
Bump version to 4.4.0.0

### PR DESCRIPTION
**Pull request by marcos-iov**
*ci:powpeg-bump*
*fit:powpeg-version-bump*

### CODE REVIEW

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Comment by marcos-iov** [comment]
pipeline:run

**Review by nathanieliov — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Review by kelvinator07 — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
