### PR TITLE
Added SyncProcessor param to Web3FederateImpl ctor

### PR DESCRIPTION
**Pull request by Vovchyk**
*rskj:eth-syncing-fix*

### CODE REVIEW

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by josedahlquist — APPROVED** [review]

**Review by marcos-iov — APPROVED** [review]

**Pull request merged**
