### PR TITLE
Fix sonar code smells

### PR DESCRIPTION
**Pull request by kelvinator07**

### CODE REVIEW

**Comment by nathanieliov** [comment]
Well done K. 

There is one more code smell. Take a look at it here: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=139&id=rsksmart_powpeg-node&open=AYZW5Y1ESC2TEwir_afZ

This is the method that is deprecated.

image

**Comment by kelvinator07** [comment]
> Well done K.
> 
> There is one more code smell. Take a look at it here: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=139&id=rsksmart_powpeg-node&open=AYZW5Y1ESC2TEwir_afZ
> 
> This is the method that is deprecated.
> 
> image

Thanks for the review Nath. Using the new verify method requires a lot of changes, so I created a ticket to address that.

**Comment by nathanieliov** [comment]
> > Well done K.
> > There is one more code smell. Take a look at it here: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=139&id=rsksmart_powpeg-node&open=AYZW5Y1ESC2TEwir_afZ
> > This is the method that is deprecated.
> > image
> 
> Thanks for the review Nath. Using the new verify method requires a lot of changes, so I created a ticket to address that.

Perfect. I'm ok with that.

**Review by nathanieliov — APPROVED** [review]
LGTM

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Pull request merged**
