### PR TITLE
Use legacy methods from PegUtilsLegacy class

### PR DESCRIPTION
**Pull request by nathanieliov**
*rskj:move-legacy-methods-to-pegUtils*

### CODE REVIEW

**Comment by marcos-iov** [comment]
Would it make sense that instead of calling the individual PegUtilsLegacy methods (isPegin, isPegout) we simply called getTransactionType?

**Comment by nathanieliov** [comment]
> Would it make sense that instead of calling the individual PegUtilsLegacy methods (isPegin, isPegout) we simply called getTransactionType?

@marcos-iov, that would be ideal. But that's not possible since the legacy getTransactionType depends on bridgeStorageProvider, which powpeg node doesn't have access to

**Comment by nathanieliov** [comment]
Closing this PR due to is duplicated. Let's continue discussions in #212

**Comment by nathanieliov** [comment]
Closing this PR due to is duplicated. Let's continue discussions at https://github.com/rsksmart/powpeg-node/pull/212

**Pull request closed without merging**
