### PR TITLE
Updating verification metadata related with RocksDb database update

### PR DESCRIPTION
**Pull request by asoto-iov**
It is needed to update the verification metadata in relation with the RocksDB library upgrade made in the RSKJ client

*rskj: upgrade_rocksDB_library*

### CODE REVIEW

**Comment by asoto-iov** [comment]
pipeline:run

**Comment by asoto-iov** [comment]
pipeline:run

**Comment by asoto-iov** [comment]
pipeline:run

**Comment by asoto-iov** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Pull request merged**
