### PR TITLE
Removed stdout message about missing native library

### PR DESCRIPTION
**Pull request by Vovchyk**
*rskj:stdout-msg-rmvl*

### CODE REVIEW

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Pull request merged**
