### PR TITLE
Hsm reduce call integration

### PR DESCRIPTION
**Pull request by marcos-iov**

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by nathanieliov — APPROVED** [review]

**Pull request merged**
