### PR TITLE
Bump version to 6.2.0.0

### PR DESCRIPTION
**Pull request by marcos-iov**
*ci:bump-6200*
*rit:bump-6200*

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by apancorb — APPROVED** [review]

**Review by wilmerrootstock — APPROVED** [review]
LGTM!

**Review by jeremy-then — COMMENTED** [review]
LGTM.

**Pull request merged**
