### PR TITLE
FINGERROOT-5.0.0-rc -> master merge

### PR DESCRIPTION
**Pull request by marcos-iov**
*fit:fingerroot500rc-master-merge*

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by nathanieliov — APPROVED** [review]

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Pull request merged**
