### PR TITLE
Version bump to 4.5.0.0

### PR DESCRIPTION
**Pull request by marcos-iov**
*fit:version-bump-4500*
*ci:version-bump-4500*

### CODE REVIEW

**Review by nathanieliov — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
