### PR TITLE
Create MIT License

### PR DESCRIPTION
**Pull request by apancorb**
## Summary

From the README.md file, the link to the License file seems to be missing: 

https://github.com/rsksmart/powpeg-node/blob/aef61b26a9861eca750cb692d0f2752b4d9cbfe7/README.md?plain=1#L361-L363

This change adds the missing MIT License generated from Github UI.

### CODE REVIEW

**Comment by apancorb** [comment]
pipeline:run

**Comment by apancorb** [comment]
pipeline:run

**Comment by apancorb** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
Added as part of https://github.com/rsksmart/powpeg-node/pull/326

**Pull request closed without merging**
