### PR TITLE
Set version to 3.0.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by marcos-iov**
*ci:version3*
*fit:new-version*

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by pamgonzalez — APPROVED** [review]

**Review by crove-iov — APPROVED** [review]
LGTM

**Pull request merged**
