### PR TITLE
Update verification metadata in regards to lib upgrade in RSKj

### PR DESCRIPTION
**Pull request by rmoreliovlabs**
Original PR: https://github.com/rsksmart/rskj/pull/1883

*rskj:upgrade-jackson-and-json-rpc-libs*

### CODE REVIEW

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Comment by rmoreliovlabs** [comment]
pipeline:run

**Review by marcos-iov — APPROVED** [review]

**Pull request merged**
