### PR TITLE
PowHSM v2+ Refactors

### PR DESCRIPTION
**Pull request by kelvinator07**

### CODE REVIEW

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by marcos-iov — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
