### PR TITLE
Refactored BtcToRskClient To Use FederatorSupport

### PR DESCRIPTION
**Pull request by kelvinator07**
*rskj:master*
*fit:master*

### CODE REVIEW

**Review by marcos-iov — DISMISSED** [review]
Great work! I think it needs a rebase in order to build properly

**Review by jeremy-then — COMMENTED** [review]
LGTM.

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Comment by marcos-iov** [comment]
pipeline:run

**Review by marcos-iov — APPROVED** [review]

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Review by josedahlquist — APPROVED** [review]

**Comment by josedahlquist** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Pull request merged**
