### PR TITLE
Bump version to 6300

### PR DESCRIPTION
**Pull request by marcos-iov**
*rit:bump-6300*

### CODE REVIEW

**Review by wilmerrootstock — APPROVED** [review]
LGTM!

**Review by apancorb — APPROVED** [review]

**Review by nathanieliov — APPROVED** [review]

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Review by julia-zack — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
